### ISSUE TITLE
执行 umi build ，dist 目录未生成 theme 相关文件，控制台报错

### ISSUE THREAD

**Issue by tomgao365** [chenshuai2144/umi-plugin-antd-theme#1]
[项目地址](https://github.com/ant-design/ant-design-pro/tree/dark)
`umi dev` 可以生成主题文件
`umi build`  产生错误信息如下：

![image](https://user-images.githubusercontent.com/13798931/65400017-66ead180-ddf2-11e9-8b78-5eae49b835bd.png)

**Comment by chenshuai2144** [comment]
fixed
