### ISSUE TITLE
Dark 主题不能正确应用到 ProTable 组件上

### ISSUE THREAD

**Issue by loocor** [chenshuai2144/umi-plugin-antd-theme#17]
### 组件环境

- "antd": "^4.0.2"
- "@ant-design/pro-layout": "^5.0.6",
- "@ant-design/pro-table": "^2.1.7",
- "umi": "^3.0.0",
- "umi-plugin-antd-theme": "^2.1.1"

### 配置数据

默认数据，即 [https://github.com/chenshuai2144/umi-plugin-antd-theme/blob/master/src/defaultTheme.ts](defaultTheme.ts) 内容

### 问题表现

-  ProTable 的内容不受 Dark 主题影响，还是浅色的；

<img width="1261" alt="02" src="https://user-images.githubusercontent.com/25772398/76701738-c4efd600-66fe-11ea-840c-a3a85a3b1a85.png">

### 期望结果

- ProTable 的颜色和设置同步；

### 参考
在 umi3 的配置中，设置为 antd: {dark: true} 后不存在上面的问题，见下图：
<img width="1420" alt="03" src="https://user-images.githubusercontent.com/25772398/76701828-adfdb380-66ff-11ea-930d-fb1e4ab54cc5.png">

**Comment by loocor** [comment]
最新的 ProTable 组件已经解决了这个问题

**Comment by xyy7260** [comment]
@loocor 请问一下我这边，安装了插件， 配置了theme.config.json  为啥没得这个按钮来切换呢?
