### ISSUE TITLE
ant v4 怎么接入动态主题啊，看了文档还是不懂

### ISSUE THREAD

**Issue by JeffreyBool** [chenshuai2144/umi-plugin-antd-theme#18]
![image](https://user-images.githubusercontent.com/24415888/77453235-f751af80-6e31-11ea-8a47-1a767bb47dfb.png)
像这种并没有说明这个文件在哪等

![image](https://user-images.githubusercontent.com/24415888/77453294-0c2e4300-6e32-11ea-82fe-beca1c4c866d.png)
这些干嘛的

**Comment by chenshuai2144** [comment]
![image](https://user-images.githubusercontent.com/8186664/77490442-d8750c80-6e75-11ea-9037-0fc4efef592e.png)

你说的是这个吗？

**Comment by JeffreyBool** [comment]
![image](https://user-images.githubusercontent.com/24415888/77492580-dc0b9200-6e7b-11ea-8ca5-2f96bbc3c4e2.png)
对，最后有个完整的例子就好啦，官方演示的代码能完整下载吗？区块下载下来这里和演示站不一样

**Comment by chenshuai2144** [comment]
执行一下 `npm fetch:blocks`

**Comment by JeffreyBool** [comment]
执行了，但是也没有看到动态主题相关的代码------------------ 原始邮件 ------------------
发件人: "陈帅"<notifications@github.com>
发送时间: 2020年3月25日(星期三) 上午9:36
收件人: "chenshuai2144/umi-plugin-antd-theme"<umi-plugin-antd-theme@noreply.github.com>;
抄送: "JeffreyBool"<1402992668@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [chenshuai2144/umi-plugin-antd-theme] ant v4 怎么接入动态主题啊，看了文档还是不懂 (#18)




 
执行一下 npm fetch:blocks
 
&mdash;
