### ISSUE TITLE
umi3版本下，开发时每次修改代码都会导致theme build，效率低下

### ISSUE THREAD

**Issue by YaoKaiPeng** [chenshuai2144/umi-plugin-antd-theme#19]
umi3版本下，开发时每次修改代码都会导致theme build，效率太低。 
能否开放配置， 不自动使用theme build

**Comment by lifeneedspassion** [comment]
我的电脑都可以煎蛋了

**Comment by chenvd** [comment]
确实有这个问题

**Comment by infnan** [comment]
建议增加一个可以配置的开关，平时能让开发人员临时禁用插件。因为build速度太慢，我们现在不得不在平时把umi-plugin-antd-theme彻底删掉，打包之前再把插件补回package.json。

**Comment by pccai** [comment]
现在这个开关有吗？

**Comment by jtbss** [comment]
totally agree !

**Comment by jtbss** [comment]
you can manually add the plugin in different environments like this. So you are unnecessary to add the plugin name back to **package.json**.
![config prod](https://user-images.githubusercontent.com/42928250/96689538-18bd4e80-13b5-11eb-893d-c101aee5b6c3.png)

**Comment by YaoKaiPeng** [comment]
> you can manually add the plugin in different environments like this. So you are unnecessary to add the plugin name back to **package.json**.
> ![config prod](https://user-images.githubusercontent.com/42928250/96690963-ea407300-13b6-11eb-874b-6c7726b6229e.png)

thx!This method should be feasible, thanks for the answer

**Comment by northdrift** [comment]
可以暂时自己写个插件，根据环境情况警用调一些插件
![image](https://user-images.githubusercontent.com/7170199/106855065-4d9ca980-66f7-11eb-8970-447cdea052e1.png)
![image](https://user-images.githubusercontent.com/7170199/106855098-5b522f00-66f7-11eb-8a87-d82fb07ab9fe.png)
