### ISSUE TITLE
老铁使用教程有木有啊

### ISSUE THREAD

**Issue by SaberPdr** [chenshuai2144/umi-plugin-antd-theme#2]
这个就一个usage, 看不懂怎么用的丫
能不能在readme里边写个简单的使用步骤啊

**Comment by SaberPdr** [comment]
主要是百度你这个插件, 一个相关结果都没有, 实在无从入手

**Comment by JerryMissTom** [comment]
@SaberPdr 我最经用到了这个插件，实现了ant design pro的主题切换，具体看下 https://juejin.im/post/5dede7556fb9a0160b637241 这篇文章

**Comment by chenshuai2144** [comment]
@SaberPdr  可以看 pro 中的使用。
https://pro.ant.design/docs/dynamic-theme-cn

**Comment by chenshuai2144** [comment]
@JerryMissTom  已点赞

**Comment by JerryMissTom** [comment]
@chenshuai2144 你们的文档我看了，说实话，和Ant Design Pro 项目实际的文件结构结合不紧密，所以导致新接触的人无从下手。

**Comment by SaberPdr** [comment]
请问window.less是less.js包里的东西吗?
我的项目里安装less之后, window对象里还是没有less, 无法使用modifyVars

**Comment by chenshuai2144** [comment]
@JerryMissTom  跪求 pr

**Comment by JerryMissTom** [comment]
@chenshuai2144 好的，我抽空搞一下。
