### ISSUE TITLE
absNodeModulesPath怎么自定义配置

### ISSUE THREAD

**Issue by huang714669** [chenshuai2144/umi-plugin-antd-theme#3]
我把antd pro套在egg里面， node moule就放在外面管理了，但是run 的时候出现路径错误， 看了下这个插件的源码，貌似是absNodeModulesPath这个变量导致的

**Comment by chenshuai2144** [comment]
absNodeModulesPath 这个是 umi 提供的

**Comment by huang714669** [comment]
明白了。
